### ISSUE TITLE
Set Up Terraform AWS Infrastructure for Keycloak

### ISSUE THREAD

**Issue by lahirujayathilake** [NASA-IMPACT/veda-auth-central#1]
### Objective
Create the AWS infrastructure required to deploy Keycloak using Terraform. This includes networking resources (VPC, subnets, security groups), ECS cluster, and RDS for the database.

```[tasklist]
### Tasks
- [x] Define the AWS VPC and subnet configurations
- [x] Create ECR repository, ECS cluster, and task definitions for Keycloak
- [x] Create a Hosted zone for veda auth deployment and generate public certificate
- [x] Set up RDS PostgreSQL as the database for Keycloak
- [x] Create an Application Load Balancer with the required target groups
- [x] Configure security groups for secure access
```

**Comment by lahirujayathilake** [comment]
Hosted Zone created for deploying veda authentication (zone id) - [Z0928161AO8DT4S0II3Z](https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones?region=us-east-2#ListRecordSets/Z0928161AO8DT4S0II3Z)
Certificate issued in us-east-2 region - arn:aws:acm:us-east-2:444055461661:certificate/ee2e60b2-aee3-435c-a05a-181081bb4f7a

**Comment by lahirujayathilake** [comment]
#19 commit addresses this issue
