### ISSUE TITLE
Develop UI designs for VEDA Auth Central

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#10]
### Description
The Veda Auth Central portal is essential for managing user authentication, profiles, and authorization. The portal empowers users to manage the authorization requirements of VEDA Apps efficiently. 

```[tasklist]
### Tasks
- [ ] Prioritize the UIs for development
- [ ] Develop the UIs for VEDA users
- [ ] Release the developed UIs for testing
- [ ] Test, fix issue,s and release
```
