### ISSUE TITLE
Objective AU-1: VEDA app teams and core auth team review and update the existing VEDA auth use cases.

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#115]
### Motivation
This PI, the core VEDA auth team, and VEDA app owners will review the existing auth use cases to assure completeness. Once the use cases are finalized, the next step is persistent documentation.

### Success Criteria 
The use cases are finalized and documented for reference. 

```[tasklist]
### Tasks
- [x] Identify VEDA App team (Data Services, JupyterHub, UI, Science Support) members to review and meet to finalize the use cases.
- [x] Core auth team and VEDA app owners will meet and review existing use cases identified by the VEDA app teams in [VEDA Auth Use Cases](https://docs.google.com/document/d/1vwqLwVSZH6ZbofWFcLC9CDVueynoVHHHCPdZLK0n1J8/edit )
- [x] Based on the review meeting, update the existing [VEDA Auth Use Cases](https://docs.google.com/document/d/1vwqLwVSZH6ZbofWFcLC9CDVueynoVHHHCPdZLK0n1J8/edit)
- [x] Decide on a template for persistent use case documentation - chose GitHub tickets
- [x] Transfer use cases to persistent Use case documentation - list of issues [here](https://github.com/NASA-IMPACT/veda-auth-central/issues?q=is%3Aissue%20label%3A%22use%20case%22%20)
- [ ] https://github.com/NASA-IMPACT/veda-auth-central/issues/120
- [ ] https://github.com/NASA-IMPACT/veda-auth-central/issues/119
```
### Risks & Dependencies

**Comment by j08lue** [comment]
Here is how far we got this PI:

- We refined the [use cases](https://github.com/NASA-IMPACT/veda-auth-central/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22use%20case%22) 
- We formulated [workflows](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/use-case-evaluation/workflows.md) that need to be completed, with an emphasis on the users who need to complete them 
- We focused on the question: **Can we provide the auth services we need and the management user experience with just the latest KeyCloak?**
- We set up a [schema](https://github.com/NASA-IMPACT/veda-auth-central/pull/141) for documenting how the workflows can be completed. 
- We produced [documentation](https://github.com/NASA-IMPACT/veda-auth-central/pull/142) for the workflow that has the most pronounced requirements towards user experience, since it needs to be completed by non-expert users

(copied from [7 Jan PM sync notes](https://docs.google.com/document/d/1dGedn9fPkRVB3n037Q54yieLYT2Be9fBjF6jVlSh2mc/edit?tab=t.0#bookmark=id.6vdcx2kxdt28))
