### ISSUE TITLE
Objective AU-2: Develop and test the use cases with Vanilla Keycloak and Custos-Enhanced Keycloak

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#117]
### Motivation
The VEDA authentication and authorization use cases will be tested with Keycloak, alongside Custos-Enhanced Keycloak, to ensure we select the most robust and secure solution for VEDA. The goal is to provide seamless access control that meets security and user experience requirements, supporting VEDA's diverse and evolving needs.

### Team & Owners
Data Services - Saadiq*, Alexandra, Anthony Lukach, Dimuthu, Lahiru
JupyterHub/Science Support  - Yuvi*, Alex, Dimuthu, Lahiru
VEDA dashboard - Anthony Boyd*, Jonas, Brian, Dimuthu, Lahiru

### Success Criteria 
The Auth use cases are tests completed on both Vanilla Keycloak and Custos-Enhanced Keycloak

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/veda-auth-central/issues/122
- [x] Decide the [evaluation criteria](https://github.com/NASA-IMPACT/veda-auth-central/pull/116/files#diff-fbb007ee8f7acf4fef86d8359c0ae88e3807f568bd77d7d555c663e5ecadea40R250) for use case testing.
- [x] Implement and test the finalized use cases using both a vanilla Keycloak setup and the Keycloak enhanced with Custos functionalities (veda-auth-central).
- [x] Document the use case test outcomes based on the evaluation criteria. (implementation complexity, challenges, and time taken for each approach to assess their practicality). Demos or videos, comparison matrix.
```
### Risks & Dependencies

**Comment by j08lue** [comment]
Vanilla KeyCloak test environment: https://github.com/NASA-IMPACT/veda-keycloak

Evaluation criteria: https://github.com/NASA-IMPACT/veda-auth-central/issues/119

Evaluation not done for all workflows yet, only WIP for Workflow 3: https://github.com/NASA-IMPACT/veda-auth-central/pull/142

**Comment by lahirujayathilake** [comment]
Use cases initial - https://github.com/NASA-IMPACT/veda-auth-central/issues/120
1st version of evaluation criteria - https://github.com/NASA-IMPACT/veda-auth-central/issues/119
Workflow document - https://docs.google.com/document/d/14UXEQWEouGRIUbI4epmbGSH2svYWbTKxjxNf3TR_ohw/edit?tab=t.0#heading=h.fn6gn5mp8wy0

**Comment by j08lue** [comment]
Current degree of completeness is sufficient for implementation in PI 25.2.
