### ISSUE TITLE
Objective AU-3: Evaluate practicality and document evaluation results from the use case testing.

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#118]
### Motivation
To ensure that the chosen authentication and authorization solution is technically sound, practical, and suitable for VEDA’s long-term needs.

### Team & Owners
Data Services - Saadiq*, Alexandra, Anthony Lukach, Dimuthu, Lahiru
JupyterHub/Science Support  - Yuvi*, Alex*, Dimuthu, Lahiru
VEDA dashboard - Anthony Boyd*, Jonas, Brian, Dimuthu, Lahiru

### Success Criteria 
Evaluation findings are documented.

```[tasklist]
### Tasks
- [x] Conduct a thorough evaluation of the practicality and effectiveness of each use case implementation. https://github.com/NASA-IMPACT/veda-auth-central/pull/138
- [ ] Compare the capabilities of vanilla Keycloak and Custos-enhanced Keycloak, running experiments to understand differences.
- [ ] Document all findings, including the comparison results and lessons learned, in both persistent documentation and an Architecture Decision Record (ADR) for reference.
```

### Risks & Dependencies
