### ISSUE TITLE
Develop a user profile management dashboard for VEDA users

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#20]
### Description
This development is for VEDA end users to manage their user profile details within VEDA.

```[tasklist]
### Tasks
- [ ] Authentication: Implement user registration and login functionality for user profile management dashboard
- [ ] Profile Information: Create UI components to display and update profile details.
- [ ] Enable adding other user attributes as needed: affiliation, research profile, etc
- [ ] Enable CRUD operations
```
