### ISSUE TITLE
Develop VEDA Auth Central (Admin Dashboard) from UX designs

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#21]
### Description
Based on the UX design, this is to develop the VEDA Auth Central based on the provided UI designs. This task involves translating the visual concepts into functional code, ensuring a seamless user experience, and implementing the necessary features.

```[tasklist]
### Tasks
- [ ]  Implement user authentication for the auth central
- [ ] Develop UIs as listed in the UX design 
- [ ] UI integration with backend APIs
- [ ] Release the implementation for testing
```
