### ISSUE TITLE
VEDA Testdrive auth prototyping against VEDA Auth Central APIs

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#22]
### Description
This issue aims to prototype authentication services for the VEDA Testdrive sample application by integrating with the provided VEDA Auth Central APIs.

```[tasklist]
### Tasks
- [x] Integrate VEDA Auth Central APIs
- [x] Test and report issues on the integration
- [x] Issue fixes and retesting
- [ ] Documentation on the integration
```

**Comment by lahirujayathilake** [comment]
Reference application - https://github.com/NASA-IMPACT/veda-auth-central/tree/main/veda-app-samples/veda-react-app
