### ISSUE TITLE
VEDA Hub auth prototyping against VEDA auth central APIs

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#24]
### Description
This issue aims to prototype authentication services for the VEDA Hub application by integrating with the provided VEDA Auth Central APIs.

```[tasklist]
### Tasks
- [ ] Integrate VEDA Auth Central APIs
- [ ] Test and report issues on the integration
- [ ] Issue fixes and retesting
- [ ] Documentation of the integration
```
