### ISSUE TITLE
Testing VEDA Auth implementation

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#28]
### Description
Preparations to test the VEDA auth integration with VEDA apps. This is a cross-functional task; each app (VEDA Hub, STAC, etc) needs to develop and execute test scenarios with central auth. The issues  are to be reported on [VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/issues)

```[tasklist]
### Tasks
- [ ] Plan the testing
- [ ] Prepare and review test scenarios
- [ ] Execution of tests
- [ ] Report issues
- [ ] Fixes and retesting.
```
