### ISSUE TITLE
Objective AU-2: Implement the centralized authorization framework necessary for VEDA apps to make app-specific decisions in enabling users and accessing resources

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#63]
## Motivation
This is the next phase in VEDA Auth Central. For VEDA, we want to make app-specific decisions about who can access what and how to enable it across VEDA Apps. VEDA Auth Central to enable Groups, Attributes, and Roles to hold the relevant information so the apps can make decisions. These components play a crucial role in allowing apps to make informed decisions about user permissions and resource access.

## Team & Owner(s)*

Lahiru*, Eroma, Brian

## Success Criteria 

- VEDA app authorization requirements are identified and documented.
- The VEDA authorization needs are designed and implemented.
- Ability to implement app-level authorization decisions based on user role, group and attributes. 
     - Use cases on the VEDA dashboard and STAC are implemented and ready for demo.

```[tasklist]
### Tasks
- [x] Document and review the identified requirements.
- [x] Implement the identified authorization features into VEDA auth.
- [x] Identify Grafana app authorization requirements
- [x] Identify STACC app authorization requirements
- [x] Implement the required additional features based on the meeting with app teams
```

## Risks/Dependencies

- A successful demo depends on VEDA app integration with Auth Central. This would need a cross-functional team effort.

**Comment by lahirujayathilake** [comment]
Grafana authorization requirements - https://github.com/NASA-IMPACT/veda-auth-central/issues/65#issuecomment-2246004496

**Comment by eroma2014** [comment]
The identified: [Groups & Scopes for VEDA Applications](https://docs.google.com/document/d/1vwqLwVSZH6ZbofWFcLC9CDVueynoVHHHCPdZLK0n1J8/edit#heading=h.pqt43d9p5xzt)

**Comment by eroma2014** [comment]
The planned AU objective is on pause due the ADR review process. The VEDA teams are in discussion.
ADR documentation
1. [Adding a Custom Layer on Top of Keycloak for Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture-decision-records/layering-on-keycloak.md)
2. [Authentication in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/1-veda-authn-flow.md)
3. [Authorization in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/2-veda-authz-flow.md)
4. [Application-Specific Administration in Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/3-vac-app-admin.md)
5. [A Customs User Portal for VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/auth-user-portal/docs/architecture-decision-records/custom-user-portal.md)

ADR discussion
1. https://github.com/NASA-IMPACT/veda-auth-central/discussions/85
2. https://github.com/NASA-IMPACT/veda-auth-central/pull/87

**Comment by eroma2014** [comment]
Closing this Objective as all tasks are completed.
