### ISSUE TITLE
Objective AU-4: VEDA Documentation: Integration Guide for the VEDA Apps and users.

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#69]
## Motivation

From VEDA app developer onboarding, admin users, end users, and operational aspects, we would need documentation. This is to make everything smooth for all users involved. We would start identifying all the documents we would need to develop, populate, and manage. Then the documentation deployment on VEDA documentation and Wiki.

## Team & Owner(s)*

Suresh*, Lahiru, Eroma

## Success Criteria 

- VEDA documentation requirements and locations are identified.
- Documentations to implement are listed and prioritized.
- Prioritized documentation for the PI is implemented and deployed in designated locations for users.

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/veda-auth-central/issues/73
- [ ] Create the identified documentation and submit it for review
- [ ] Consult the Science support team on publishing the documentation
- [ ] Publish the documentation as relevant to the intended audience
```

## Risks/Dependencies

Documentation is an ongoing task. We need VEDA members to assist in reviewing and providing feedback before making it public. The effort and time could stretch beyond the PI.

**Comment by eroma2014** [comment]
The planned AU objective is on pause due the ADR review process. The VEDA teams are in discussion.
ADR documentation
1. [Adding a Custom Layer on Top of Keycloak for Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture-decision-records/layering-on-keycloak.md)
2. [Authentication in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/1-veda-authn-flow.md)
3. [Authorization in VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/2-veda-authz-flow.md)
4. [Application-Specific Administration in Veda Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/main/docs/architecture/3-vac-app-admin.md)
5. [A Customs User Portal for VEDA Auth Central](https://github.com/NASA-IMPACT/veda-auth-central/blob/auth-user-portal/docs/architecture-decision-records/custom-user-portal.md)

ADR discussion
1. https://github.com/NASA-IMPACT/veda-auth-central/discussions/85
2. https://github.com/NASA-IMPACT/veda-auth-central/pull/87
